"""initial_schema

Revision ID: 5f7af73e7161
Revises: 
Create Date: 2026-09-26 13:23:35.193822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f7af73e7161'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('permissions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('badge_number', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_audit_id'), 'audit_logs', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('case_number', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('jurisdiction', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('stored_filename', sa.String(length=256), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_reference', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('source_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_sha256_hash'), 'evidence', ['sha256_hash'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('storage_reference', sa.String(length=512), nullable=False),
    sa.Column('verification_code', sa.String(length=64), nullable=False),
    sa.Column('report_sha256', sa.String(length=64), nullable=False),
    sa.Column('qr_code_data', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_reports_report_sha256'), 'reports', ['report_sha256'], unique=True)
    op.create_index(op.f('ix_reports_verification_code'), 'reports', ['verification_code'], unique=True)
    op.create_table('analysis_results',
    sa.Column('analysis_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prediction', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_analysis_results_analysis_id'), 'analysis_results', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_evidence_id'), 'analysis_results', ['evidence_id'], unique=False)
    op.create_table('correlation_links',
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('source_evidence_id', sa.String(length=64), nullable=False),
    sa.Column('target_evidence_id', sa.String(length=64), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence.evidence_id'], ),
    sa.ForeignKeyConstraint(['target_evidence_id'], ['evidence.evidence_id'], ),
    sa.PrimaryKeyConstraint('correlation_id')
    )
    op.create_index(op.f('ix_correlation_links_case_id'), 'correlation_links', ['case_id'], unique=False)
    op.create_index(op.f('ix_correlation_links_correlation_id'), 'correlation_links', ['correlation_id'], unique=False)
    op.create_table('custody_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_custody_evid_seq', 'custody_events', ['evidence_id', 'sequence_number'], unique=True)
    op.create_index(op.f('ix_custody_events_event_hash'), 'custody_events', ['event_hash'], unique=True)
    op.create_index(op.f('ix_custody_events_event_id'), 'custody_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_custody_events_evidence_id'), 'custody_events', ['evidence_id'], unique=False)
    op.create_table('evidence_metadata',
    sa.Column('metadata_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('format_valid', sa.Boolean(), nullable=False),
    sa.Column('magic_bytes', sa.String(length=64), nullable=False),
    sa.Column('exif_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('timestamps_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('anomalies', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ),
    sa.PrimaryKeyConstraint('metadata_id')
    )
    op.create_index(op.f('ix_evidence_metadata_evidence_id'), 'evidence_metadata', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_evidence_metadata_metadata_id'), 'evidence_metadata', ['metadata_id'], unique=False)
    op.create_table('explainability_records',
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('confidence_category', sa.String(length=32), nullable=False),
    sa.Column('feature_attributions', sa.Text(), nullable=True),
    sa.Column('limitations_disclaimer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_explainability_records_evidence_id'), 'explainability_records', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_explainability_records_record_id'), 'explainability_records', ['record_id'], unique=False)
    op.create_table('verification_records',
    sa.Column('verification_id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('verification_method', sa.String(length=64), nullable=False),
    sa.Column('verifier_identifier', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_index(op.f('ix_verification_records_report_id'), 'verification_records', ['report_id'], unique=False)
    op.create_index(op.f('ix_verification_records_timestamp'), 'verification_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_verification_records_verification_id'), 'verification_records', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_records_verification_id'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_timestamp'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_report_id'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_explainability_records_record_id'), table_name='explainability_records')
    op.drop_index(op.f('ix_explainability_records_evidence_id'), table_name='explainability_records')
    op.drop_table('explainability_records')
    op.drop_index(op.f('ix_evidence_metadata_metadata_id'), table_name='evidence_metadata')
    op.drop_index(op.f('ix_evidence_metadata_evidence_id'), table_name='evidence_metadata')
    op.drop_table('evidence_metadata')
    op.drop_index(op.f('ix_custody_events_evidence_id'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_event_id'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_event_hash'), table_name='custody_events')
    op.drop_index('idx_custody_evid_seq', table_name='custody_events')
    op.drop_table('custody_events')
    op.drop_index(op.f('ix_correlation_links_correlation_id'), table_name='correlation_links')
    op.drop_index(op.f('ix_correlation_links_case_id'), table_name='correlation_links')
    op.drop_table('correlation_links')
    op.drop_index(op.f('ix_analysis_results_evidence_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_analysis_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_reports_verification_code'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_sha256'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_evidence_sha256_hash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_audit_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
